FROM registry.access.redhat.com/ubi8/openjdk-21@sha256:0dfc6248dfa2ac87ede63f1ccb909c374f7f6bccdd91f72a18ba85845f4600b2 AS builder

USER 0
RUN microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y git

WORKDIR /work
COPY ./ .

RUN git config --global --add safe.directory /work && mvn -e -V -B package -Dmaven.test.skip=true

FROM registry.access.redhat.com/ubi8/openjdk-21-runtime@sha256:65f22b1ef70e257dbe26b1ac7e393df8ca9ec9e45b9204819a81aec15acbb3ae
WORKDIR /work/

COPY --from=builder /work/LICENSE /licenses/
COPY --from=builder /work/target/quarkus-app/lib/ /deployments/lib/
COPY --from=builder /work/target/quarkus-app/*.jar /deployments/
COPY --from=builder /work/target/quarkus-app/app/ /deployments/app/
COPY --from=builder /work/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185

ENV AB_JOLOKIA_OFF=""
ENV JAVA_OPTS="-Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
