FROM registry.access.redhat.com/ubi8/openjdk-21@sha256:3f712e2b11fea22b81636747175d68830b5cba527c2dff9172d143b9acc5612e AS builder

USER 0
RUN microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y git

WORKDIR /work
COPY ./ .

RUN git config --global --add safe.directory /work && mvn -e -V -B package -Dmaven.test.skip=true

FROM registry.access.redhat.com/ubi8/openjdk-21-runtime@sha256:418b3b6f9bc41ba969a6c7a20b06831131e30d6b4140e29a9453c6a4f08f8c21

USER 0
RUN microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y util-linux

WORKDIR /work/

COPY --from=builder /work/target/quarkus-app/lib/ /deployments/lib/
COPY --from=builder /work/target/quarkus-app/*.jar /deployments/
COPY --from=builder /work/target/quarkus-app/app/ /deployments/app/
COPY --from=builder /work/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185

ENV AB_JOLOKIA_OFF=""
ENV JAVA_OPTS="-Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
